// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Quantify.Core.Data;

#nullable disable

namespace Quantify.Migrations
{
    [DbContext(typeof(QuantifyDbContext))]
    [Migration("20260812164133_UpdateModelsForSeeder")]
    partial class UpdateModelsForSeeder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Quantify.Core.Models.Answer", b =>
                {
                    b.Property<int>("AnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AnswerId"));

                    b.Property<string>("Content")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("tinyint(1)");

                    b.Property<long>("MathTaskId")
                        .HasColumnType("bigint");

                    b.HasKey("AnswerId");

                    b.HasIndex("MathTaskId");

                    b.ToTable("Answer");
                });

            modelBuilder.Entity("Quantify.Core.Models.Approach", b =>
                {
                    b.Property<long>("ApproachId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("ApproachId"));

                    b.Property<bool>("Passed")
                        .HasColumnType("tinyint(1)");

                    b.Property<long>("StudentTaskProgressId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("TimeStarted")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ApproachId");

                    b.HasIndex("StudentTaskProgressId");

                    b.ToTable("Approach");
                });

            modelBuilder.Entity("Quantify.Core.Models.LearningMaterials", b =>
                {
                    b.Property<long>("MaterialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("MaterialId"));

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long?>("TopicId")
                        .HasColumnType("bigint");

                    b.HasKey("MaterialId");

                    b.HasIndex("TopicId");

                    b.ToTable("LearningMaterials");
                });

            modelBuilder.Entity("Quantify.Core.Models.MathTask", b =>
                {
                    b.Property<long>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("TaskId"));

                    b.Property<long?>("AuthorId")
                        .HasColumnType("bigint");

                    b.Property<string>("Contents")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ExpReward")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("PointsCount")
                        .HasColumnType("int");

                    b.Property<long>("TopicId")
                        .HasColumnType("bigint");

                    b.HasKey("TaskId");

                    b.HasIndex("AuthorId");

                    b.HasIndex("TopicId");

                    b.ToTable("MathTasks");
                });

            modelBuilder.Entity("Quantify.Core.Models.Module", b =>
                {
                    b.Property<long>("ModuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("ModuleId"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("ModuleId");

                    b.HasIndex("Name");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("Quantify.Core.Models.StudentTaskProgress", b =>
                {
                    b.Property<long>("StudentTaskProgressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("StudentTaskProgressId"));

                    b.Property<int>("ApproachNumber")
                        .HasColumnType("int");

                    b.Property<float>("Average")
                        .HasColumnType("float");

                    b.Property<bool>("Passed")
                        .HasColumnType("tinyint(1)");

                    b.Property<long?>("StudentId")
                        .HasColumnType("bigint");

                    b.Property<long>("TaskId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("StudentTaskProgressId");

                    b.HasIndex("StudentId");

                    b.HasIndex("TaskId");

                    b.ToTable("StudentTaskProgress");
                });

            modelBuilder.Entity("Quantify.Core.Models.Topic", b =>
                {
                    b.Property<long>("TopicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("TopicId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("ModuleId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("TopicId");

                    b.HasIndex("ModuleId");

                    b.HasIndex("Name");

                    b.ToTable("Topic");
                });

            modelBuilder.Entity("Quantify.Core.Users.Opinion", b =>
                {
                    b.Property<long>("OpinionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("OpinionId"));

                    b.Property<int>("StarsCount")
                        .HasColumnType("int");

                    b.Property<long?>("TutorId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserOpinion")
                        .HasColumnType("longtext");

                    b.HasKey("OpinionId");

                    b.HasIndex("TutorId");

                    b.ToTable("Opinion");
                });

            modelBuilder.Entity("Quantify.Core.Users.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Permission")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("Surname")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NickName")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasDiscriminator().HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("StudentTutor", b =>
                {
                    b.Property<long>("StudentsId")
                        .HasColumnType("bigint");

                    b.Property<long>("TutorsId")
                        .HasColumnType("bigint");

                    b.HasKey("StudentsId", "TutorsId");

                    b.HasIndex("TutorsId");

                    b.ToTable("StudentTutor");
                });

            modelBuilder.Entity("Quantify.Core.Users.Admin", b =>
                {
                    b.HasBaseType("Quantify.Core.Users.User");

                    b.HasDiscriminator().HasValue("Admin");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Email = "kristinadubiaha07@gmail.com",
                            IsDeleted = false,
                            NickName = "admin",
                            PasswordHash = "AQAAAAIAAYagAAAAEC3l6G992jUBBhCMy0mw+aZ44tpfIpaSzTgo7H6/sJY4ne8exn4uAfVkVzNEsMgqUg==",
                            Permission = 1
                        });
                });

            modelBuilder.Entity("Quantify.Core.Users.Student", b =>
                {
                    b.HasBaseType("Quantify.Core.Users.User");

                    b.Property<long>("CoinsCount")
                        .HasColumnType("bigint");

                    b.HasDiscriminator().HasValue("Student");
                });

            modelBuilder.Entity("Quantify.Core.Users.Tutor", b =>
                {
                    b.HasBaseType("Quantify.Core.Users.User");

                    b.Property<string>("AboutTutor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EmploymentPlace")
                        .HasColumnType("longtext");

                    b.Property<string>("Experience")
                        .HasColumnType("longtext");

                    b.HasDiscriminator().HasValue("Tutor");
                });

            modelBuilder.Entity("Quantify.Core.Models.Answer", b =>
                {
                    b.HasOne("Quantify.Core.Models.MathTask", null)
                        .WithMany("AllAnswers")
                        .HasForeignKey("MathTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Quantify.Core.Models.Approach", b =>
                {
                    b.HasOne("Quantify.Core.Models.StudentTaskProgress", "Progress")
                        .WithMany("Attempts")
                        .HasForeignKey("StudentTaskProgressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Progress");
                });

            modelBuilder.Entity("Quantify.Core.Models.LearningMaterials", b =>
                {
                    b.HasOne("Quantify.Core.Models.Topic", null)
                        .WithMany("AdditionalLearningMaterials")
                        .HasForeignKey("TopicId");
                });

            modelBuilder.Entity("Quantify.Core.Models.MathTask", b =>
                {
                    b.HasOne("Quantify.Core.Users.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId");

                    b.HasOne("Quantify.Core.Models.Topic", "Topic")
                        .WithMany("MathTasks")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("Quantify.Core.Models.StudentTaskProgress", b =>
                {
                    b.HasOne("Quantify.Core.Users.Student", null)
                        .WithMany("Approaches")
                        .HasForeignKey("StudentId");

                    b.HasOne("Quantify.Core.Models.MathTask", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Quantify.Core.Models.Topic", b =>
                {
                    b.HasOne("Quantify.Core.Models.Module", "Module")
                        .WithMany("Topics")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("Quantify.Core.Users.Opinion", b =>
                {
                    b.HasOne("Quantify.Core.Users.Tutor", null)
                        .WithMany("Opinions")
                        .HasForeignKey("TutorId");
                });

            modelBuilder.Entity("StudentTutor", b =>
                {
                    b.HasOne("Quantify.Core.Users.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Quantify.Core.Users.Tutor", null)
                        .WithMany()
                        .HasForeignKey("TutorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Quantify.Core.Models.MathTask", b =>
                {
                    b.Navigation("AllAnswers");
                });

            modelBuilder.Entity("Quantify.Core.Models.Module", b =>
                {
                    b.Navigation("Topics");
                });

            modelBuilder.Entity("Quantify.Core.Models.StudentTaskProgress", b =>
                {
                    b.Navigation("Attempts");
                });

            modelBuilder.Entity("Quantify.Core.Models.Topic", b =>
                {
                    b.Navigation("AdditionalLearningMaterials");

                    b.Navigation("MathTasks");
                });

            modelBuilder.Entity("Quantify.Core.Users.Student", b =>
                {
                    b.Navigation("Approaches");
                });

            modelBuilder.Entity("Quantify.Core.Users.Tutor", b =>
                {
                    b.Navigation("Opinions");
                });
#pragma warning restore 612, 618
        }
    }
}
